# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Outlook-Message
version:      0.902
version_from: lib/Email/Outlook/Message.pm
installdirs:  site
requires:
    Carp:                          0
    Date::Format:                  2.22
    Email::MIME::ContentType:      1.014
    Email::MIME::Creator:          1.454
    Email::MIME::Modifier:         1.442
    Email::Simple:                 2.003
    IO::All:                       0
    OLE::Storage_Lite:             0.14
    POSIX:                         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
