---
abstract: 'Read Outlook .msg files'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4208, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Email-Outlook-Message
provides:
  Email::Outlook::Message:
    file: lib/Email/Outlook/Message.pm
    version: '0.915'
  Email::Outlook::Message::AddressInfo:
    file: lib/Email/Outlook/Message/AddressInfo.pm
    version: '0.915'
  Email::Outlook::Message::Attachment:
    file: lib/Email/Outlook/Message/Attachment.pm
    version: '0.915'
  Email::Outlook::Message::Base:
    file: lib/Email/Outlook/Message/Base.pm
    version: '0.915'
requires:
  Carp: '0'
  Email::MIME: '1.923'
  Email::MIME::ContentType: '1.014'
  Email::Sender: '1.3'
  Email::Simple: '2.102'
  Encode: '0'
  File::Basename: '0'
  Getopt::Long: '0'
  IO::All: '0'
  OLE::Storage_Lite: '0.14'
  POSIX: '0'
  Pod::Usage: '0'
  Test::More: '0'
  perl: '5.006'
resources:
  license: http://dev.perl.org/licenses/
version: '0.915'
