---
name: Email-Outlook-Message
version: 0.910
author:
  - 'Matijs van Zuijlen, C<matijs@matijs.net>'
abstract: Read Outlook .msg files
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Email::MIME::ContentType: 1.014
  Email::MIME::Creator: 1.454
  Email::MIME::Modifier: 1.442
  Email::Simple: 2.003
  Encode: 0
  IO::All: 0
  OLE::Storage_Lite: 0.14
  POSIX: 0
  Test::More: 0
  perl: 5.006
configure_requires:
  Module::Build: 0.340201
provides:
  Email::Outlook::Message:
    file: lib/Email/Outlook/Message.pm
    version: 0.910
  Email::Outlook::Message::AddressInfo:
    file: lib/Email/Outlook/Message.pm
  Email::Outlook::Message::Attachment:
    file: lib/Email/Outlook/Message.pm
  Email::Outlook::Message::Base:
    file: lib/Email/Outlook/Message.pm
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
